# Generated by Django 2.1.4 on 2020-01-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rafreportusecategory_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_notified',
            field=models.BooleanField(default=True, help_text='Automatic e-mail notifications are not sent if set to false', verbose_name='is notified'),
        ),
    ]
