# Generated by Django 2.1.4 on 2020-02-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_is_notified'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpComRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_number', models.CharField(max_length=256)),
                ('body', models.CharField(max_length=1024)),
                ('topic', models.CharField(max_length=512)),
                ('excerpt', models.CharField(max_length=32768)),
                ('table_data', models.CharField(blank=True, default='', max_length=32768)),
                ('resulting_decisions', models.CharField(blank=True, max_length=128)),
                ('link_to_report', models.URLField(max_length=512)),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imp_com_recommendations', to='core.ReportingPeriod')),
            ],
            options={
                'verbose_name_plural': 'Implementation Committee Recommendations',
                'db_table': 'implementation_committee_recommendations',
                'ordering': ('reporting_period',),
            },
        ),
        migrations.CreateModel(
            name='TEAPIndicativeNumberOfReports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_reports', models.CharField(max_length=256)),
                ('remarks', models.CharField(blank=True, max_length=512)),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.ReportingPeriod')),
            ],
            options={
                'verbose_name_plural': 'TEAP indicative numbers of reports',
                'db_table': 'teap_indicative_number_of_reports',
                'ordering': ('reporting_period',),
            },
        ),
        migrations.CreateModel(
            name='TEAPReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, null=True)),
                ('issue', models.CharField(max_length=256)),
                ('request_by_parties', models.CharField(max_length=1024)),
                ('report_to_be_produced', models.CharField(blank=True, max_length=256)),
                ('remark_issue_type', models.CharField(blank=True, max_length=512)),
                ('remark_issue', models.CharField(blank=True, max_length=512)),
                ('remark_request', models.CharField(blank=True, max_length=512)),
                ('remark_report', models.CharField(blank=True, max_length=512)),
                ('decision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='teap_reports', to='core.Decision')),
            ],
            options={
                'verbose_name_plural': 'TEAP reports',
                'db_table': 'teap_report',
                'ordering': ('sort_order',),
            },
        ),
        migrations.CreateModel(
            name='TEAPReportType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(default=0, null=True)),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
            options={
                'verbose_name_plural': 'TEAP reports',
                'db_table': 'teap_report_type',
                'ordering': ('sort_order',),
            },
        ),
        migrations.AddField(
            model_name='licensingsystem',
            name='kigali_licensing_system_reported',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='licensingsystem',
            name='kigali_licensing_system_status',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='licensingsystem',
            name='kigali_ratification_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='teapreport',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teap_reports', to='core.TEAPReportType'),
        ),
        migrations.AddField(
            model_name='teapreport',
            name='reporting_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teap_reports', to='core.ReportingPeriod'),
        ),
    ]
