# Generated by Django 2.1.4 on 2020-02-12 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_impcom_teap_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessAgentDecision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_validity_start_date', models.DateField(null=True)),
                ('application_validity_end_date', models.DateField(null=True)),
                ('emit_limits_validity_start_date', models.DateField(null=True)),
                ('emit_limits_validity_end_date', models.DateField(null=True)),
                ('decision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pa_decisions', to='core.Decision')),
            ],
            options={
                'verbose_name_plural': 'process agent decisions',
                'db_table': 'pa_decision',
            },
        ),
        migrations.AddField(
            model_name='processagentapplication',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pa_applications', to='core.ProcessAgentDecision'),
        ),
        migrations.AddField(
            model_name='processagentemissionlimit',
            name='decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pa_emission_limits', to='core.ProcessAgentDecision'),
        ),
    ]
