# Generated by Django 2.1.4 on 2020-02-04 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20200204_1121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impcomrecommendation',
            options={'ordering': ('reporting_period',), 'verbose_name': 'IMPCOM Recommendation', 'verbose_name_plural': 'IMPCOM Recommendations'},
        ),
        migrations.AlterModelOptions(
            name='teapreport',
            options={'ordering': ('sort_order',), 'verbose_name': 'TEAP report', 'verbose_name_plural': 'TEAP reports'},
        ),
        migrations.AlterModelOptions(
            name='teapreporttype',
            options={'ordering': ('sort_order',), 'verbose_name_plural': 'TEAP report types'},
        ),
        migrations.AlterModelTable(
            name='impcomrecommendation',
            table='impcom_recommendations',
        ),
    ]
