# Generated by Django 2.1.4 on 2020-02-13 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_pa_decision_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processagentapplicationvalidity',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='processagentemissionlimitvalidity',
            name='decision',
        ),
        migrations.RemoveField(
            model_name='processagentapplication',
            name='validity',
        ),
        migrations.RemoveField(
            model_name='processagentemissionlimit',
            name='validity',
        ),
        migrations.DeleteModel(
            name='ProcessAgentApplicationValidity',
        ),
        migrations.DeleteModel(
            name='ProcessAgentEmissionLimitValidity',
        ),
    ]
