# Generated by Django 2.1.4 on 2020-02-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20200204_1711'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impcombody',
            options={'ordering': ('sort_order', 'name'), 'verbose_name': 'IMPCOM Body', 'verbose_name_plural': 'IMPCOM Bodies'},
        ),
        migrations.AlterField(
            model_name='impcombody',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='impcomtopic',
            name='name',
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
