# Generated by Django 2.1.4 on 2020-02-18 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_pa_validities'),
    ]

    operations = [
        migrations.AddField(
            model_name='processagentusesreported',
            name='pa_decision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.ProcessAgentDecision'),
        ),
    ]
