# Generated by Django 2.1.4 on 2020-02-05 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20200204_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impcomrecommendation',
            options={'ordering': ('-reporting_period', 'sort_order'), 'verbose_name': 'IMPCOM Recommendation', 'verbose_name_plural': 'IMPCOM Recommendations'},
        ),
        migrations.AddField(
            model_name='impcomrecommendation',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
