# Generated by Django 2.1.4 on 2020-02-18 08:31

from django.db import migrations


def populate_pa_decision(apps, schema_editor):
    ProcessAgentUsesReported = apps.get_model(
        'core', 'ProcessAgentUsesReported'
    )
    ProcessAgentDecision = apps.get_model('core', 'ProcessAgentDecision')
    for use in ProcessAgentUsesReported.objects.all():
        use.pa_decision = ProcessAgentDecision.objects.filter(
            decision=use.decision
        ).first()
        use.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_processagentusesreported_pa_decision'),
    ]

    operations = [
        migrations.RunPython(populate_pa_decision),
    ]
