# Generated by Django 2.1.4 on 2020-02-24 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_remove_old_decision_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaselineLimitPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('can_run_baselines_tool', 'Can run baselines tool'), ('can_run_limits_tool', 'Can run limits tool')),
                'managed': False,
                'default_permissions': [],
            },
        ),
    ]
