# Generated by Django 2.1.4 on 2020-02-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_adminactions_perms'),
    ]

    operations = [
        migrations.AddField(
            model_name='processagentusesreported',
            name='contain_technologies_text',
            field=models.TextField(blank=True),
        ),
    ]
