# Generated by Django 2.1.4 on 2020-02-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_contain_technologies_data_migration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processagentusesreported',
            name='contain_technologies',
        ),
        migrations.RenameField(
            model_name='processagentusesreported',
            old_name='contain_technologies_text',
            new_name='contain_technologies',
        ),
        migrations.DeleteModel(
            name='ProcessAgentContainTechnology',
        ),
    ]
