# Generated by Django 2.1.4 on 2020-02-27 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_replace_old_contain_tech_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processagentusesreported',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pa_uses_reported', to='core.Submission'),
        ),
    ]
