# Generated by Django 2.1.4 on 2020-02-29 07:10

from django.db import migrations
from django.db.models import F


def populate_party_period(apps, schema_editor):
    ProcessAgentUsesReported = apps.get_model(
        'core', 'ProcessAgentUsesReported'
    )
    # Cannot use QS 'update' to reference foreign-key fields
    for p in ProcessAgentUsesReported.objects.filter(submission__isnull=False):
        p.party = p.submission.party
        p.reporting_period = p.submission.reporting_period
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_uses_reported_party_period'),
    ]

    operations = [
        migrations.RunPython(populate_party_period),
    ]
