# Generated by Django 2.1.4 on 2020-03-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_party_period_data_migration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvedcriticaluse',
            options={'verbose_name_plural': 'EUN/CUN Approved critical use categories'},
        ),
        migrations.AlterModelOptions(
            name='criticalusecategory',
            options={'ordering': ('name',), 'verbose_name_plural': 'EUN/CUN Critical use categories'},
        ),
        migrations.AlterModelOptions(
            name='exemptionapproved',
            options={'verbose_name_plural': 'EUN/CUN Approved exemptions'},
        ),
        migrations.AlterModelOptions(
            name='nomination',
            options={'verbose_name_plural': 'EUN/CUN Nominations'},
        ),
        migrations.AlterField(
            model_name='criticalusecategory',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
