# Generated by Django 2.1.4 on 2020-03-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20200305_1954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teapreport',
            options={'ordering': ('reporting_period__name', 'report_type__sort_order', 'sort_order'), 'verbose_name': 'TEAP report', 'verbose_name_plural': 'TEAP reports'},
        ),
        migrations.AlterField(
            model_name='historicalsubmission',
            name='_workflow_class',
            field=models.CharField(choices=[('empty', 'Empty'), ('base', 'Base'), ('default', 'Default'), ('accelerated', 'Accelerated'), ('simplified', 'Simplified'), ('default_exemption', 'Default_exemption'), ('accelerated_exemption', 'Accelerated_exemption'), ('default_transfer', 'Default_transfer'), ('default_process_agent', 'Default_process_agent')], db_column='workflow_class', default='empty', max_length=32),
        ),
        migrations.AlterField(
            model_name='submission',
            name='_workflow_class',
            field=models.CharField(choices=[('empty', 'Empty'), ('base', 'Base'), ('default', 'Default'), ('accelerated', 'Accelerated'), ('simplified', 'Simplified'), ('default_exemption', 'Default_exemption'), ('accelerated_exemption', 'Accelerated_exemption'), ('default_transfer', 'Default_transfer'), ('default_process_agent', 'Default_process_agent')], db_column='workflow_class', default='empty', max_length=32),
        ),
    ]
