# Generated by Django 2.1.4 on 2020-03-19 13:48

from django.db import migrations, models
import ozone.core.models.country_profile


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_workflow_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licensingsystemfile',
            name='file',
            field=models.FileField(upload_to=ozone.core.models.country_profile.get_licensing_system_file_upload_to),
        ),
        migrations.AlterField(
            model_name='othercountryprofiledata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ozone.core.models.country_profile.get_other_country_profile_upload_to),
        ),
        migrations.AlterField(
            model_name='website',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=ozone.core.models.country_profile.get_website_upload_to),
        ),
        migrations.AlterUniqueTogether(
            name='othercountryprofiledata',
            unique_together={('party', 'reporting_period', 'obligation')},
        ),
    ]
