# Generated by Django 2.1.4 on 2020-04-23 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_removing_unneeded_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartyGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('parties', models.ManyToManyField(to='core.Party')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='is_cap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='party_group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='core.PartyGroup'),
        ),
    ]
