# Generated by Django 2.1.4 on 2020-05-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20200423_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_mobile_app',
            field=models.BooleanField(default=False),
        ),
    ]
