# Generated by Django 2.1.4 on 2020-05-12 08:07

from django.db import migrations
import ozone.core.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_user_is_mobile_app'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ozone.core.models.user.UserManager()),
            ],
        ),
    ]
