# Generated by Django 2.1.4 on 2020-05-28 15:30

from django.db import migrations
from django.db.models import F


def populate_revision_major_minor(apps, schema_editor):
    Submission = apps.get_model('core', 'Submission')

    Submission.objects.update(
        revision_major=F('version'),
        revision_minor=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_major_minor_revision'),
    ]

    operations = [
        migrations.RunPython(populate_revision_major_minor),
    ]
