# Generated by Django 2.1.4 on 2020-05-28 15:30

from django.db import migrations
from django.db.models import F


def populate_revision_major_minor(apps, schema_editor):
    Submission = apps.get_model('core', 'Submission')

    # Data entry submissions will not have a revision set
    Submission.objects.filter(
        obligation__has_versions=True
    ).exclude(
        _current_state='data_entry'
    ).update(
        revision_major=F('version'),
        revision_minor=0,
    )


def clear_revision_major_minor(apps, schema_editor):
    Submission = apps.get_model('core', 'Submission')

    Submission.objects.filter(
        obligation__has_versions=True
    ).exclude(
        _current_state='data_entry'
    ).update(
        revision_major=None,
        revision_minor=None
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_major_minor_revision'),
    ]

    operations = [
        migrations.RunPython(
            populate_revision_major_minor,
            reverse_code=clear_revision_major_minor
        ),
    ]
