# Generated by Django 2.1.4 on 2020-05-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_revision_major_minor_data_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubmission',
            name='date_reported_f',
            field=models.DateField(blank=True, help_text='Date at which substances under Annex F were reported.', null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='date_reported_f',
            field=models.DateField(blank=True, help_text='Date at which substances under Annex F were reported.', null=True),
        ),
    ]
