# Generated by Django 2.1.4 on 2020-06-05 10:41

from django.db import migrations, models
import ozone.core.models.utils


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_date_reported_f_not_mandatory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submissioninfo',
            name='email',
            field=models.CharField(blank=True, max_length=128, null=True, validators=[ozone.core.models.utils.validate_multiple_emails]),
        ),
    ]
