# Generated by Django 2.1.4 on 2020-07-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_submission_info_multi_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='blend',
            name='is_contained_in_polyols',
            field=models.BooleanField(default=False),
        ),
    ]
