# Generated by Django 2.1.4 on 2020-06-26 08:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_submission_info_multi_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActualBaselineAndLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baseline_prod', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('baseline_cons', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('baseline_bdn', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('limit_prod', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('limit_cons', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('limit_bdn', models.DecimalField(blank=True, decimal_places=15, max_digits=25, null=True, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_baselines', to='core.Group')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_baselines', to='core.Party')),
                ('reporting_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='actual_baselines', to='core.ReportingPeriod')),
            ],
            options={
                'db_table': 'actual_baseline',
            },
        ),
    ]
