# Generated by Django 2.1.4 on 2020-06-26 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_actualbaselineandlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualbaselineandlimit',
            name='is_article5',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='actualbaselineandlimit',
            name='is_eu_member',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='prodcons',
            name='actual_baseline_and_limit',
            field=models.ForeignKey(blank=True, help_text='Actual baselines and limits for this aggregation', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prodcons_aggregations', to='core.ActualBaselineAndLimit'),
        ),
    ]
